In [1]:
import pandas as pd
import numpy as np
cancer = pd.read_csv("ovariantotal.csv")
cancer.head()

AFP     AG  Age   ALB  ALP  ALT  AST  BASO#  BASO%   BUN  ...   PCT  \
0   3.58  19.36   47  45.4   56   11   24   0.01   0.30  5.35  ...  0.09   
1  34.24  23.98   61  39.9   95    9   13   0.02   0.30  3.21  ...  0.30   
2   1.50  18.40   39  45.4   77    9   18   0.03   0.60  3.80  ...  0.13   
3   2.75  16.60   45  39.2   26   16   17   0.05   0.74  5.27  ...  0.25   
4   2.36  19.97   45  35.0   47   21   27   0.01   0.10  4.89  ...  0.28   

    PDW  PHOS  PLT   RBC   RDW  TBIL    TP     UA  TYPE  
0  13.4  1.46   74  2.64  13.7   5.5  73.9  396.4     0  
1  11.2  1.09  304  4.89  12.7   6.8  72.0  119.2     0  
2  15.2  0.97  112  4.62  12.0  14.8  77.9  209.2     0  
3  17.4  1.25  339  4.01  14.6  10.9  66.1  215.6     0  
4  11.9  0.94  272  4.40  13.4   5.3  66.5  206.0     0  

[5 rows x 50 columns]

In [2]:
X=cancer.drop('TYPE',axis=1)
y=cancer['TYPE']

In [3]:
pd.DataFrame(X,columns=cancer.columns[:-1])

AFP     AG  Age   ALB  ALP  ALT  AST  BASO#  BASO%   BUN  ...    NEU  \
0     3.58  19.36   47  45.4   56   11   24   0.01   0.30  5.35  ...  76.20   
1    34.24  23.98   61  39.9   95    9   13   0.02   0.30  3.21  ...  76.50   
2     1.50  18.40   39  45.4   77    9   18   0.03   0.60  3.80  ...  69.70   
3     2.75  16.60   45  39.2   26   16   17   0.05   0.74  5.27  ...  65.50   
4     2.36  19.97   45  35.0   47   21   27   0.01   0.10  4.89  ...  59.50   
..     ...    ...  ...   ...  ...  ...  ...    ...    ...   ...  ...    ...   
344   2.09  20.91   52  48.6   65   40   30   0.00   0.00  4.29  ...  66.58   
345   2.00  12.14   37  46.1   49    9   20   0.00   0.00  3.12  ...  66.58   
346   2.83  19.23   59  45.8   83    9   16   0.02   0.60  4.38  ...  66.58   
347   1.84  27.22   30  47.8   64   26   22   0.03   0.30  3.61  ...  66.58   
348   1.61  13.00   39  44.9   68    7   13   0.01   0.20  4.38  ...  66.58   

      PCT   PDW  PHOS  PLT   RBC   RDW  TBIL    TP     UA  
0    0.09  13.4  1.46   74  2.64  13.7   5.5  73.9  396.4  
1    0.30  11.2  1.09  304  4.89  12.7   6.8  72.0  119.2  
2    0.13  15.2  0.97  112  4.62  12.0  14.8  77.9  209.2  
3    0.25  17.4  1.25  339  4.01  14.6  10.9  66.1  215.6  
4    0.28  11.9  0.94  272  4.40  13.4   5.3  66.5  206.0  
..    ...   ...   ...  ...   ...   ...   ...   ...    ...  
344  0.22  10.8  0.99  219  4.56  11.9  10.7  80.4  241.5  
345  0.31  17.3  0.95  262  4.24  17.7  17.2  73.5  240.5  
346  0.21  10.4  1.00  221  4.89  11.6  13.8  68.4  209.5  
347  0.42  13.4  1.31  398  5.35  12.5  11.3  76.0  285.7  
348  0.23  11.0  1.10  224  4.13  12.1   8.3  68.6  184.9  

[349 rows x 49 columns]

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [5]:
from sklearn.ensemble import GradientBoostingClassifier
gradient_booster = GradientBoostingClassifier(learning_rate=0.1)
gradient_booster.fit(X_train,y_train)
y_pred_gradboost=gradient_booster.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred_gradboost))
print(accuracy_score(y_test,y_pred_gradboost))
print(classification_report(y_test,y_pred_gradboost))

[[34  7]
 [ 2 27]]
0.8714285714285714
              precision    recall  f1-score   support

           0       0.94      0.83      0.88        41
           1       0.79      0.93      0.86        29

    accuracy                           0.87        70
   macro avg       0.87      0.88      0.87        70
weighted avg       0.88      0.87      0.87        70



In [6]:
from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier()
abc.fit(X_train, y_train)
y_pred_abc = abc.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred_abc))
print(accuracy_score(y_test,y_pred_abc))
print(classification_report(y_test,y_pred_abc))

[[36  5]
 [ 1 28]]
0.9142857142857143
              precision    recall  f1-score   support

           0       0.97      0.88      0.92        41
           1       0.85      0.97      0.90        29

    accuracy                           0.91        70
   macro avg       0.91      0.92      0.91        70
weighted avg       0.92      0.91      0.91        70



In [7]:
from xgboost import XGBClassifier
model = XGBClassifier(learning_rate=1)
model.fit(X_train,y_train)
y_pred_xgb=model.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred_xgb))
print(accuracy_score(y_test,y_pred_xgb))
print(classification_report(y_test,y_pred_xgb))

[[34  7]
 [ 1 28]]
0.8857142857142857
              precision    recall  f1-score   support

           0       0.97      0.83      0.89        41
           1       0.80      0.97      0.88        29

    accuracy                           0.89        70
   macro avg       0.89      0.90      0.88        70
weighted avg       0.90      0.89      0.89        70



In [8]:
from catboost import CatBoostClassifier
model1 = CatBoostClassifier()
model1.fit(X_train,y_train)
y_pred_cat=model1.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred_cat))
print(accuracy_score(y_test,y_pred_cat))
print(classification_report(y_test,y_pred_cat))

Learning rate set to 0.005973
0:	learn: 0.6884179	total: 158ms	remaining: 2m 37s
1:	learn: 0.6826573	total: 170ms	remaining: 1m 24s
2:	learn: 0.6789849	total: 180ms	remaining: 59.8s
3:	learn: 0.6737940	total: 191ms	remaining: 47.4s
4:	learn: 0.6686697	total: 198ms	remaining: 39.3s
5:	learn: 0.6630322	total: 205ms	remaining: 34s
6:	learn: 0.6571231	total: 217ms	remaining: 30.8s
7:	learn: 0.6508149	total: 224ms	remaining: 27.7s
8:	learn: 0.6458282	total: 230ms	remaining: 25.3s
9:	learn: 0.6398923	total: 237ms	remaining: 23.4s
10:	learn: 0.6343662	total: 242ms	remaining: 21.8s
11:	learn: 0.6293189	total: 248ms	remaining: 20.4s
12:	learn: 0.6248376	total: 253ms	remaining: 19.2s
13:	learn: 0.6207332	total: 256ms	remaining: 18s
14:	learn: 0.6159770	total: 259ms	remaining: 17s
15:	learn: 0.6098612	total: 264ms	remaining: 16.2s
16:	learn: 0.6059047	total: 269ms	remaining: 15.6s
17:	learn: 0.6018824	total: 275ms	remaining: 15s
18:	learn: 0.5976083	total: 279ms	remaining: 14.4s
19:	learn: 0.5932

190:	learn: 0.2384707	total: 943ms	remaining: 4s
191:	learn: 0.2376000	total: 948ms	remaining: 3.99s
192:	learn: 0.2366501	total: 952ms	remaining: 3.98s
193:	learn: 0.2358314	total: 956ms	remaining: 3.97s
194:	learn: 0.2347134	total: 960ms	remaining: 3.96s
195:	learn: 0.2340415	total: 963ms	remaining: 3.95s
196:	learn: 0.2330117	total: 966ms	remaining: 3.94s
197:	learn: 0.2318907	total: 970ms	remaining: 3.93s
198:	learn: 0.2314463	total: 974ms	remaining: 3.92s
199:	learn: 0.2306240	total: 977ms	remaining: 3.91s
200:	learn: 0.2293715	total: 981ms	remaining: 3.9s
201:	learn: 0.2283959	total: 985ms	remaining: 3.89s
202:	learn: 0.2277732	total: 989ms	remaining: 3.88s
203:	learn: 0.2269477	total: 992ms	remaining: 3.87s
204:	learn: 0.2260864	total: 995ms	remaining: 3.86s
205:	learn: 0.2251362	total: 999ms	remaining: 3.85s
206:	learn: 0.2242937	total: 1s	remaining: 3.84s
207:	learn: 0.2236774	total: 1.01s	remaining: 3.83s
208:	learn: 0.2230381	total: 1.01s	remaining: 3.83s
209:	learn: 0.22238

354:	learn: 0.1450636	total: 1.54s	remaining: 2.8s
355:	learn: 0.1446474	total: 1.55s	remaining: 2.8s
356:	learn: 0.1442727	total: 1.55s	remaining: 2.79s
357:	learn: 0.1439443	total: 1.55s	remaining: 2.79s
358:	learn: 0.1436272	total: 1.56s	remaining: 2.78s
359:	learn: 0.1431848	total: 1.56s	remaining: 2.78s
360:	learn: 0.1428469	total: 1.57s	remaining: 2.77s
361:	learn: 0.1425662	total: 1.57s	remaining: 2.77s
362:	learn: 0.1421465	total: 1.57s	remaining: 2.76s
363:	learn: 0.1417660	total: 1.58s	remaining: 2.75s
364:	learn: 0.1415263	total: 1.58s	remaining: 2.75s
365:	learn: 0.1411646	total: 1.58s	remaining: 2.74s
366:	learn: 0.1407240	total: 1.59s	remaining: 2.74s
367:	learn: 0.1404626	total: 1.59s	remaining: 2.73s
368:	learn: 0.1402835	total: 1.59s	remaining: 2.73s
369:	learn: 0.1397877	total: 1.6s	remaining: 2.72s
370:	learn: 0.1393408	total: 1.6s	remaining: 2.71s
371:	learn: 0.1389545	total: 1.6s	remaining: 2.71s
372:	learn: 0.1387442	total: 1.61s	remaining: 2.7s
373:	learn: 0.1384

513:	learn: 0.1013919	total: 2.12s	remaining: 2s
514:	learn: 0.1012776	total: 2.12s	remaining: 2s
515:	learn: 0.1010390	total: 2.13s	remaining: 2s
516:	learn: 0.1006373	total: 2.14s	remaining: 2s
517:	learn: 0.1003066	total: 2.14s	remaining: 1.99s
518:	learn: 0.1000622	total: 2.15s	remaining: 1.99s
519:	learn: 0.0998497	total: 2.15s	remaining: 1.99s
520:	learn: 0.0997080	total: 2.15s	remaining: 1.98s
521:	learn: 0.0994507	total: 2.16s	remaining: 1.98s
522:	learn: 0.0991007	total: 2.16s	remaining: 1.97s
523:	learn: 0.0989307	total: 2.17s	remaining: 1.97s
524:	learn: 0.0987181	total: 2.17s	remaining: 1.96s
525:	learn: 0.0984291	total: 2.17s	remaining: 1.96s
526:	learn: 0.0981335	total: 2.18s	remaining: 1.96s
527:	learn: 0.0980363	total: 2.18s	remaining: 1.95s
528:	learn: 0.0977237	total: 2.19s	remaining: 1.95s
529:	learn: 0.0976710	total: 2.19s	remaining: 1.94s
530:	learn: 0.0973791	total: 2.19s	remaining: 1.94s
531:	learn: 0.0972480	total: 2.2s	remaining: 1.93s
532:	learn: 0.0970979	tot

678:	learn: 0.0736925	total: 2.7s	remaining: 1.28s
679:	learn: 0.0736449	total: 2.71s	remaining: 1.27s
680:	learn: 0.0735130	total: 2.71s	remaining: 1.27s
681:	learn: 0.0734027	total: 2.71s	remaining: 1.26s
682:	learn: 0.0732070	total: 2.72s	remaining: 1.26s
683:	learn: 0.0730272	total: 2.72s	remaining: 1.26s
684:	learn: 0.0728222	total: 2.72s	remaining: 1.25s
685:	learn: 0.0726234	total: 2.73s	remaining: 1.25s
686:	learn: 0.0725057	total: 2.73s	remaining: 1.24s
687:	learn: 0.0723500	total: 2.73s	remaining: 1.24s
688:	learn: 0.0722182	total: 2.74s	remaining: 1.24s
689:	learn: 0.0721064	total: 2.74s	remaining: 1.23s
690:	learn: 0.0719472	total: 2.74s	remaining: 1.23s
691:	learn: 0.0718450	total: 2.75s	remaining: 1.22s
692:	learn: 0.0716151	total: 2.75s	remaining: 1.22s
693:	learn: 0.0714950	total: 2.75s	remaining: 1.21s
694:	learn: 0.0713262	total: 2.76s	remaining: 1.21s
695:	learn: 0.0712057	total: 2.76s	remaining: 1.21s
696:	learn: 0.0710003	total: 2.76s	remaining: 1.2s
697:	learn: 0.

844:	learn: 0.0547141	total: 3.7s	remaining: 679ms
845:	learn: 0.0545541	total: 3.71s	remaining: 676ms
846:	learn: 0.0544379	total: 3.72s	remaining: 673ms
847:	learn: 0.0543632	total: 3.75s	remaining: 673ms
848:	learn: 0.0542695	total: 3.79s	remaining: 674ms
849:	learn: 0.0541656	total: 3.81s	remaining: 673ms
850:	learn: 0.0540843	total: 3.83s	remaining: 671ms
851:	learn: 0.0539870	total: 3.85s	remaining: 668ms
852:	learn: 0.0539497	total: 3.86s	remaining: 665ms
853:	learn: 0.0538580	total: 3.87s	remaining: 662ms
854:	learn: 0.0537657	total: 3.88s	remaining: 658ms
855:	learn: 0.0536850	total: 3.89s	remaining: 654ms
856:	learn: 0.0536078	total: 3.9s	remaining: 651ms
857:	learn: 0.0535366	total: 3.93s	remaining: 650ms
858:	learn: 0.0533979	total: 3.96s	remaining: 650ms
859:	learn: 0.0533543	total: 3.99s	remaining: 649ms
860:	learn: 0.0532373	total: 4.01s	remaining: 647ms
861:	learn: 0.0531344	total: 4.02s	remaining: 644ms
862:	learn: 0.0530515	total: 4.03s	remaining: 641ms
863:	learn: 0.